package jdbc25.prepared;

import java.sql.SQLException;

import jdbc25.service.IConnectImpl;

public class InsertSQLAutoGeneratedKey extends IConnectImpl {

	@Override
	public void execute() throws Exception {
		//1.데이타베이스 연결
		connect(ORACLE_URL, "JDBC", "JDBC");
		//2.PreparedStatement객체 생성
		psmt = conn.prepareStatement("INSERT INTO bbs(no,title,id) VALUES(SEQ_BBS.NEXTVAL,?,?)", new String[] {"no"});
		//3.인파라미터 설정
		psmt.setString(1, getValue("제목"));
		psmt.setString(2, getValue("아이디"));
		try {
			//4.쿼리 실행
			System.out.println(psmt.executeUpdate()+"행이 입력됨.");
			//5.입력된 행의 Key가져오기
			rs=psmt.getGeneratedKeys();
			rs.next();
			System.out.println("입력된 행의 키값:"+rs.getInt(1));
		}
		catch(SQLException e) {
			System.out.println("입력시 오류:"+e.getMessage());
		}
		finally {
			//6.자원반납
			close();
		}
	}/////////execute
	
	public static void main(String[] args) throws Exception {
		new InsertSQLAutoGeneratedKey().execute();
	}/////////main

}////////////class
